# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xa7a12tcpg238-2I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/verilog_files/Image_Processing/Image_Processing.cache/wt [current_project]
set_property parent.project_path G:/verilog_files/Image_Processing/Image_Processing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/box_blur_filter.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/con_sobel_pipe_stage.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/contrast_dec.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/contrast_inc.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/gaussian_blur_filter.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/inversion.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/line_buffer.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/line_buffer_controller.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/mac_sobel_pipe_stage.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/neighborhood_processing.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_MAC.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_MAC_gblur.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_MAC_sharp.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_buff_gblur.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_conv.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_conv_gblur.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/pipe_stage_conv_sharp.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/point_processing.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/rgb2gray.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/sharpen_filter.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/sobel_filter.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/thresh_sobel_pipe_stage.v
  G:/verilog_files/Image_Processing/Image_Processing.srcs/sources_1/new/image_processing_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top image_processing_top -part xa7a12tcpg238-2I


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef image_processing_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file image_processing_top_utilization_synth.rpt -pb image_processing_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
